### ISSUE TITLE
Coverage Reporting "Unknown" Percentage

### ISSUE THREAD

**Issue by dgrahn** [serut/meteor-coverage#48]
When I navigate to the `/coverage` page, the percentage is reported as "Unknown".

## Expected Behavior
It should report a coverage.

## Current Behavior
It reports "Unknown"

## Steps to Reproduce (for bugs)
~~~
{
    "coverage": {
        "coverage_app_folder": "/home/ubuntu/workspace/",
        "is_coverage_active": true,
        "verbose": false
    }
}
~~~

Running with
`meteor test --driver-package practicalmeteor:mocha --settings .coverage.json`

Let me know if you need additional information.

**Comment by serut** [comment]
Several things that can explain why the coverage is not collected:

- your meteor app is not in that folder `/home/ubuntu/workspace/`. Can you confirm this path `/home/ubuntu/workspace/.meteor` is correct ?
- did you open the page with tests results ? Did you execute the javascript command to send the client coverage collected to the server before opening the report page?
- last idea, try spacejam. It should work...

**Comment by dgrahn** [comment]
Ok. I decided to try `spacejam`. This is in my `package.json`

~~~
  "scripts": {
    "start": "meteor run --settings settings.json",

    "test": "meteor npm run lint:fix & meteor npm run test:app-unit & ...",
    "test:app-unit": "meteor test --driver-package practicalmeteor:mocha-console-runner",
    "test:app-unit-watch": "meteor test --driver-package practicalmeteor:mocha",
    "test:app-full-watch": "meteor test --full-app --driver-package practicalmeteor:mocha",
    "test:packages-watch": "meteor test-packages --driver-package practicalmeteor:mocha",

    "precoverage": "npm run lint",
    "coverage": "meteor npm run coverage:app-unit && meteor npm run coverage:app-full",
    "coverage:app-unit": "spacejam test --coverage 'out_lcovonly out_coverage out_html' --driver-package practicalmeteor:mocha-console-runner",
    "coverage:app-full": "spacejam test --full-app --coverage 'out_lcovonly out_coverage out_html in_coverage' --driver-package practicalmeteor:mocha-console-runner",
    "precoverage-watch": "npm run lint",
    "coverage-watch:app-unit": "meteor test --settings settings.coverage.json --driver-package practicalmeteor:mocha",
    "coverage-watch:app-full": "meteor test --full-app --settings settings.coverage.json --driver-package practicalmeteor:mocha",
    "pretest": "npm run lint",
    "test": "meteor npm run test:app-unit && meteor npm run test:app-full",
    "test:app-unit": "spacejam test --driver-package practicalmeteor:mocha-console-runner",
    "test:app-full": "spacejam test --full-app --driver-package practicalmeteor:mocha-console-runner",
    "pretest-watch": "npm run lint",
    "test-watch:app-unit": "meteor test --driver-package practicalmeteor:mocha-console-runner",
    "test-watch:app-full": "meteor test --full-app  --driver-package practicalmeteor:mocha-console-runner",

    "coverage:packages": "spacejam test-packages ./ --coverage out_lcovonly --driver-package practicalmeteor:mocha-console-runner",
    "coverage-watch": "meteor npm run lint:fix & meteor npm run coverage-watch:packages",
    "coverage-watch:packages": "meteor test-packages --settings settings.coverage.json  --driver-package practicalmeteor:mocha-console-runner",
    "test": "meteor npm run test:packages",
    "test:packages": "meteor test-packages ./ --coverage out_lcovonly --driver-package practicalmeteor:mocha-console-runner",

    "lint": "eslint . || exit 0;",
    "lint:fix": "eslint --fix ."
  },
~~~

This is the output of `spacejam-mocha`

~~~
spacejam: spawning meteor
[[[[[ Tests ]]]]]

=> Started proxy.
=> Started MongoDB.
spacejam: meteor mongodb is ready
=> Started your app.
=> App running at: http://localhost:4096/
spacejam: meteor is ready
spacejam: spawning phantomjs
Fontconfig warning: ignoring C.UTF-8: not a valid language tag
phantomjs: Running tests at http://localhost:4096/local using test-in-console
I20170413-11:29:49.959(0)? MochaRunner.runServerTests: Starting server side tests with run id PALX9eoXz63LwTfnd
W20170413-11:29:50.015(0)? (STDERR) MochaRunner.runServerTests: failures: 0

--------------------------------------------------
---------------------RESULTS----------------------
PASSED: 0
FAILED: 0
SKIPPED: 0
TOTAL: 0
--------------------------------------------------
--------------------------------------------------

spacejam: phantomjs exited with code: 0
spacejam: killing meteor
spacejam: meteor killed with signal: SIGTERM
spacejam: All tests have passed. Exiting.
~~~

I find this surprising, because I do have tests.

**Comment by serut** [comment]
- can you clone https://github.com/serut/meteor-coverage-app-exemple and try it on your computer ? 
- did you try to run `coverage:app-unit` or  `coverage:app-full` ? 
- how did you installed spacejam ?

**Comment by dgrahn** [comment]
1. Here are the results from running the command `spacejam test-packages --driver-package=practicalmeteor:mocha-conso`

~~~
le-runner
spacejam: spawning meteor
spacejam: killing meteor
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: spawn meteor ENOENT
  at exports._errnoException (util.js:907:11)
  at Process.ChildProcess._handle.onexit (internal/child_process.js:189:32)
  at onErrorNT (internal/child_process.js:355:16)
  at nextTickCallbackWith2Args (node.js:458:9)
  at process._tickCallback (node.js:372:17)
  at Function.Module.runMain (module.js:443:11)
  at startup (node.js:139:18)
  at node.js:990:3
~~~

2. Here are the results for the command `spacejam test coverage:app-unit`

~~~
dgrahn:~/workspace (master) $ spacejam test coverage:app-unit
spacejam: spawning meteor
[[[[[ Tests ]]]]]

=> Started proxy.
=> Started MongoDB.
spacejam: meteor mongodb is ready
I20170413-14:36:56.850(0)? ** You've set up some data subscriptions with Meteor.publish(), but
I20170413-14:36:57.000(0)? ** you still have autopublish turned on. Because autopublish is still
I20170413-14:36:57.000(0)? ** on, your Meteor.publish() calls won't have much effect. All data
I20170413-14:36:57.001(0)? ** will still be sent to all clients.
I20170413-14:36:57.001(0)? **
I20170413-14:36:57.002(0)? ** Turn off autopublish by removing the autopublish package:
I20170413-14:36:57.002(0)? **
I20170413-14:36:57.002(0)? **   $ meteor remove autopublish
I20170413-14:36:57.003(0)? **
I20170413-14:36:57.003(0)? ** .. and make sure you have Meteor.publish() and Meteor.subscribe() calls
I20170413-14:36:57.003(0)? ** for each collection that you want clients to see.
I20170413-14:36:57.003(0)? 
W20170413-14:36:57.370(0)? (STDERR) /home/ubuntu/.meteor/packages/meteor-tool/.1.4.4_1.t6z2q0++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20170413-14:36:57.370(0)? (STDERR)                                             throw(ex);
W20170413-14:36:57.371(0)? (STDERR)                                             ^
W20170413-14:36:57.371(0)? (STDERR) 
W20170413-14:36:57.371(0)? (STDERR) Error: Can't find test driver package: test-in-console
W20170413-14:36:57.372(0)? (STDERR)     at packages/meteor.js:1031:13
W20170413-14:36:57.372(0)? (STDERR)     at Function.time (/tmp/meteor-test-rundxffsu/.meteor/local/build/programs/server/profile.js:309:28)
W20170413-14:36:57.372(0)? (STDERR)     at /tmp/meteor-test-rundxffsu/.meteor/local/build/programs/server/boot.js:312:13
W20170413-14:36:57.372(0)? (STDERR)     at /tmp/meteor-test-rundxffsu/.meteor/local/build/programs/server/boot.js:353:5
W20170413-14:36:57.373(0)? (STDERR)     at Function.run (/tmp/meteor-test-rundxffsu/.meteor/local/build/programs/server/profile.js:510:12)
W20170413-14:36:57.373(0)? (STDERR)     at /tmp/meteor-test-rundxffsu/.meteor/local/build/programs/server/boot.js:351:11
=> Exited with code: 1
W20170413-14:37:01.485(0)? (STDERR) /home/ubuntu/.meteor/packages/meteor-tool/.1.4.4_1.t6z2q0++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20170413-14:37:01.486(0)? (STDERR)                                             throw(ex);
W20170413-14:37:01.486(0)? (STDERR)                                             ^
W20170413-14:37:01.486(0)? (STDERR) 
W20170413-14:37:01.487(0)? (STDERR) Error: Can't find test driver package: test-in-console
W20170413-14:37:01.487(0)? (STDERR)     at packages/meteor.js:1031:13
W20170413-14:37:01.487(0)? (STDERR)     at Function.time (/tmp/meteor-test-rundxffsu/.meteor/local/build/programs/server/profile.js:309:28)
W20170413-14:37:01.487(0)? (STDERR)     at /tmp/meteor-test-rundxffsu/.meteor/local/build/programs/server/boot.js:312:13
W20170413-14:37:01.488(0)? (STDERR)     at /tmp/meteor-test-rundxffsu/.meteor/local/build/programs/server/boot.js:353:5
W20170413-14:37:01.488(0)? (STDERR)     at Function.run (/tmp/meteor-test-rundxffsu/.meteor/local/build/programs/server/profile.js:510:12)
W20170413-14:37:01.489(0)? (STDERR)     at /tmp/meteor-test-rundxffsu/.meteor/local/build/programs/server/boot.js:351:11
=> Exited with code: 1
W20170413-14:37:05.476(0)? (STDERR) /home/ubuntu/.meteor/packages/meteor-tool/.1.4.4_1.t6z2q0++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20170413-14:37:05.477(0)? (STDERR)                                             throw(ex);
W20170413-14:37:05.477(0)? (STDERR)                                             ^
W20170413-14:37:05.477(0)? (STDERR) 
W20170413-14:37:05.478(0)? (STDERR) Error: Can't find test driver package: test-in-console
W20170413-14:37:05.478(0)? (STDERR)     at packages/meteor.js:1031:13
W20170413-14:37:05.478(0)? (STDERR)     at Function.time (/tmp/meteor-test-rundxffsu/.meteor/local/build/programs/server/profile.js:309:28)
W20170413-14:37:05.479(0)? (STDERR)     at /tmp/meteor-test-rundxffsu/.meteor/local/build/programs/server/boot.js:312:13
W20170413-14:37:05.480(0)? (STDERR)     at /tmp/meteor-test-rundxffsu/.meteor/local/build/programs/server/boot.js:353:5
W20170413-14:37:05.480(0)? (STDERR)     at Function.run (/tmp/meteor-test-rundxffsu/.meteor/local/build/programs/server/profile.js:510:12)
W20170413-14:37:05.481(0)? (STDERR)     at /tmp/meteor-test-rundxffsu/.meteor/local/build/programs/server/boot.js:351:11
=> Exited with code: 1
=> Your application is crashing. Waiting for file change.
spacejam: meteor has errors
spacejam: killing meteor
spacejam: meteor killed with signal: SIGTERM
spacejam: meteor is crashing server side. Exiting.
~~~

3. `npm install spacejam`

Here is my workspace if you would like to play around with it. https://ide.c9.io/dgrahn/meteor-coverage-test

**Comment by serut** [comment]
I can't execute terminal commands on cloud9.

You need to:

- clone the repo
- run `meteor npm install`
- never run `npm install spacejam` otherwise it installs the wrong version of spacejam
- run `meteor npm update`
then you can run any type of test
Like what circle.ci does to run tests : https://github.com/serut/meteor-coverage-app-exemple/blob/master/circle.yml

**Comment by dgrahn** [comment]
I've given you read/write privileges. I will try that set of commands.

**Comment by serut** [comment]
Now it works.

- never run `npm install spacejam`
- never run `npm [...]` directly, you need to execute command threw meteor: `meteor npm [...]`
- **you needed to install meteor** `curl https://install.meteor.com | /bin/sh`
- in the project you have cloned, there is flow-router, a router with a huge bug while testing. So then I runned `git submodule update --init` to install a `flow-router` fork inside `packages` directory that doesn't prevent test to succeed (meteor search first inside packages directory, then in atmosphere)
- `meteor npm install` 
- done !
